-- Comprehensive Peptide Data
-- This file contains detailed information for all peptides including mechanisms, dosing, benefits, etc.

-- Clear existing peptides (optional - comment out if you want to preserve existing data)
-- TRUNCATE TABLE peptides CASCADE;

-- Weight Loss & Metabolic Peptides
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon) VALUES
(
  'Semaglutide',
  '2mg, 5mg, 10mg, 15mg, 20mg, 30mg',
  'Various',
  'Weight Loss & Metabolic',
  'A GLP-1 receptor agonist originally developed for type 2 diabetes management but widely researched for obesity due to its potent appetite suppression and metabolic effects.',
  'GLP-1 receptor agonist that suppresses appetite via hypothalamic signaling, slows gastric emptying, and promotes insulin release while inhibiting glucagon.',
  '7 days',
  'Store in refrigerator (2-8°C)',
  '["Average weight loss of 15-20% over 68 weeks in trials", "Improves glycemic control and cardiovascular risk factors", "Enhances satiety and reduces cravings", "Supports fat oxidation and insulin sensitivity"]'::jsonb,
  '["Injection site reactions (redness, swelling)", "Nausea, vomiting, diarrhea, constipation", "Fatigue, abdominal pain, decreased appetite", "Rare: Pancreatitis, gallbladder disease, thyroid tumors"]'::jsonb,
  '["Do not use if pregnant, breastfeeding, or history of medullary thyroid carcinoma/MEN 2", "Avoid in type 1 diabetes, severe GI disease, or hypersensitivity"]'::jsonb,
  '[{"vialSize": "3MG", "reconstitution": "Mix with 0.6mL (60 units) BAC water", "frequency": "Dose once weekly subcutaneously. Stay 4 weeks per dose before increasing", "subcutaneous": "4 units = 0.25mg; 8 units = 0.5mg; 12 units = 0.75mg; 16 units = 1mg; 24 units = 1.5mg; 32 units = 2mg; 40 units = 2.5mg"}, {"vialSize": "10MG", "reconstitution": "Mix with 2mL (200 units) BAC water", "frequency": "Dose once weekly subcutaneously", "subcutaneous": "10 units = 0.5mg; 20 units = 1mg; 30 units = 1.5mg; 40 units = 2mg; 50 units = 2.5mg; 60 units = 3mg"}]'::jsonb,
  '["Tirzepatide: Dual GLP-1/GIP for enhanced weight loss", "Cagrilintide: Amylin analog for amplified satiety", "AOD-9604: Boosts lipolysis", "BPC-157: Mitigates GI side effects"]'::jsonb,
  '💊'
),
(
  'Tirzepatide',
  '5mg, 10mg, 15mg, 20mg, 30mg, 40mg, 50mg, 60mg',
  'Various',
  'Weight Loss & Metabolic',
  'A dual agonist of the GLP-1 and GIP receptors originally developed to treat Type-2 diabetes but has since become a leading anti-obesity medication.',
  'Dual agonist of GLP-1 and GIP receptors. GLP-1 suppresses appetite and increases feelings of fullness. GIP promotes insulin secretion and supports energy balance.',
  '5 days',
  'Store in refrigerator (2-8°C)',
  '["Average weight loss of 24.7% after 72 weeks", "Reduces appetite and cravings", "Enhances satiety and energy balance", "Supports fat oxidation and metabolism", "Improves insulin sensitivity and blood sugar control"]'::jsonb,
  '["Injection site reaction (redness, swelling, itching)", "Nausea, vomiting, diarrhea, constipation", "Decreased appetite, fatigue, dyspepsia", "Abdominal pain, burping (may have sulfur smell)", "Hair loss", "Rare: Thyroid C-Cell Tumors, Pancreatitis, Gastroparesis"]'::jsonb,
  '["Do not use if pregnant or breastfeeding", "Do not use with personal or family history of Medullary Thyroid Carcinoma or MEN 2", "Do not use if you have Type-1 diabetes, diabetic retinopathy, or severe GI disease", "Do not use if allergic or hypersensitive to Tirzepatide"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix with 0.5mL (or 50 units) of BAC water", "frequency": "Dose 1 day of each week (once every 7 days), always on the same day of the week. Stay on each dose for a minimum of 4 weeks before raising", "subcutaneous": "12 units = 2.5mg; 25 units = 5mg; 38 units = 7.5mg; 50 units = 10mg", "notes": "Those transferring from another GLP peptide should start at 5mg, NOT 2.5mg"}, {"vialSize": "30MG", "reconstitution": "Mix with 1.5mL (or 150 units) of BAC water", "frequency": "Dose 1 day of each week (once every 7 days), always on the same day of the week. Stay on each dose for a minimum of 4 weeks before increasing", "subcutaneous": "12 units = 2.5mg; 25 units = 5mg; 38 units = 7.5mg; 50 units = 10mg; 63 units = 12.5mg; 75 units = 15mg", "notes": "Those transferring from another GLP peptide should start at 5mg, NOT 2.5mg"}]'::jsonb,
  '["AOD-9604: enhances fat breakdown and further accelerates weight loss", "Tesamorelin: synergistic for fat reduction, especially visceral fat", "Semax or Selank: manage mood and cognitive function", "NAD+ or MOTS-C: support energy and mitochondrial efficiency", "BPC-157: beneficial for gut repair if experiencing GI discomfort", "CJC-1295 / Ipamorelin: for muscle maintenance and enhanced metabolic recovery"]'::jsonb,
  '💊'
),
(
  'Retatrutide',
  '5mg, 10mg, 15mg, 20mg, 30mg',
  'Various',
  'Weight Loss & Metabolic',
  'A powerful triple agonist peptide that targets GLP-1, GIP, and glucagon receptors—making it the most comprehensive metabolic peptide in its class.',
  'Triple agonist peptide targeting GLP-1, GIP, and glucagon receptors. GLP-1 suppresses appetite and enhances satiety. GIP boosts insulin secretion and fat metabolism. Glucagon increases energy expenditure and hepatic fat oxidation.',
  '6 days',
  'Store in refrigerator (2-8°C)',
  '["Superior weight loss (up to 24% in 48 weeks)", "Improves glycemic control and liver fat reduction", "Enhances metabolic rate and cardiovascular health", "Rapid and sustained fat loss"]'::jsonb,
  '["Gastrointestinal issues (nausea, diarrhea)", "Injection site reactions", "Fatigue, mild heart rate increase", "Rare: Pancreatitis, thyroid concerns"]'::jsonb,
  '["Avoid in pregnancy, breastfeeding, or thyroid cancer history", "Not for type 1 diabetes or severe GI disorders", "Hypersensitivity to components"]'::jsonb,
  '[{"vialSize": "6MG", "reconstitution": "Mix with 1.2mL (120 units) BAC water", "frequency": "Dose weekly subcutaneously, titrate from 1mg over 4 weeks", "subcutaneous": "20 units = 1mg; 40 units = 2mg; 60 units = 3mg; 80 units = 4mg; 100 units = 5mg; 120 units = 6mg"}, {"vialSize": "12MG", "reconstitution": "Mix with 2.4mL (240 units) BAC water", "frequency": "Dose weekly subcutaneously", "subcutaneous": "40 units = 2mg; 80 units = 4mg; 120 units = 6mg; 160 units = 8mg; 200 units = 10mg; 240 units = 12mg"}]'::jsonb,
  '["Semaglutide: For dual GLP-1 enhancement", "Glutathione: For detox support and liver optimization", "LIPO-C: To enhance energy and fat breakdown", "BPC-157: Gut protection from GI effects"]'::jsonb,
  '💊'
);

-- Tissue Repair & Healing Peptides
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon) VALUES
(
  'BPC-157',
  '5mg, 10mg',
  'Various',
  'Healing & Recovery',
  'A synthetic peptide derived from a protein in human gastric juice, researched for its regenerative effects on tissues throughout the body.',
  'Synthetic peptide derived from a protein in human gastric juice. Upregulates growth factors, enhances angiogenesis, and protects GI mucosa.',
  '4-6 hours',
  'Store in refrigerator (2-8°C)',
  '["Accelerates tendon, ligament, muscle, and GI healing", "Reduces inflammation", "Systemic repair support"]'::jsonb,
  '["Minimal; possible injection site reactions"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "5MG", "reconstitution": "Mix with 2mL (200 units) BAC water", "frequency": "Dose daily subcutaneously", "subcutaneous": "250-500mcg (25-50 units) daily"}, {"vialSize": "10MG", "reconstitution": "Mix with 4mL (400 units) BAC water", "frequency": "Dose daily subcutaneously", "subcutaneous": "250-500mcg (10-20 units) daily"}]'::jsonb,
  '["TB-500: Synergistic repair", "GHK-Cu: Skin and connective tissue"]'::jsonb,
  '🩹'
),
(
  'TB-500',
  '5mg, 10mg',
  'Various',
  'Healing & Recovery',
  'A synthetic version of Thymosin Beta-4, a peptide involved in actin regulation for tissue repair and healing.',
  'Synthetic version of Thymosin Beta-4, a peptide involved in actin regulation for tissue repair. Promotes actin polymerization for cell migration, angiogenesis, and anti-inflammatory effects.',
  '2-4 hours',
  'Store in refrigerator (2-8°C)',
  '["Accelerates muscle, tendon, and wound healing", "Improves flexibility and reduces scarring", "Enhances recovery"]'::jsonb,
  '["Headaches, nausea, injection site reactions"]'::jsonb,
  '["Cancer history (angiogenesis risk)"]'::jsonb,
  '[{"vialSize": "5MG", "reconstitution": "Mix with 2.5mL (250 units) BAC water", "frequency": "Loading: 4-8mg/week divided 2-3x", "subcutaneous": "Loading: 4-8mg/week (8-16 units 2x/week)"}, {"vialSize": "10MG", "reconstitution": "Mix with 5mL (500 units) BAC water", "frequency": "Loading: 4-8mg/week divided 2-3x", "subcutaneous": "Loading: 4-8mg/week (4-8 units 2x/week)"}]'::jsonb,
  '["BPC-157: Comprehensive healing", "GHK-Cu: Collagen support"]'::jsonb,
  '🩹'
),
(
  'Ipamorelin',
  '5mg, 10mg',
  'Various',
  'Growth Hormone',
  'A selective growth hormone secretagogue and ghrelin receptor agonist, promoting GH release without cortisol/prolactin spikes.',
  'Selective growth hormone secretagogue and ghrelin receptor agonist, promoting GH release without cortisol/prolactin spikes.',
  '2 hours',
  'Store in refrigerator (2-8°C)',
  '["Increases GH for muscle growth and recovery", "Improves sleep and metabolism", "Enhances energy"]'::jsonb,
  '["Mild hunger, flushing", "Injection site reactions"]'::jsonb,
  '["Hypersensitivity, active malignancy"]'::jsonb,
  '[{"vialSize": "5MG", "reconstitution": "Mix with 1mL (100 units) BAC water", "frequency": "Dose nightly subcutaneously, 5 days/week", "subcutaneous": "100-300mcg (2-6 units) nightly"}, {"vialSize": "10MG", "reconstitution": "Mix with 2mL (200 units) BAC water", "frequency": "Dose nightly subcutaneously, 5 days/week", "subcutaneous": "100-300mcg (2-6 units) nightly"}]'::jsonb,
  '["CJC-1295: Synergistic GH release", "Tesamorelin: Fat reduction"]'::jsonb,
  '🩹'
),
(
  'CJC-1295 With DAC',
  '5mg, 10mg',
  'Various',
  'Growth Hormone',
  'A long-acting growth hormone-releasing hormone (GHRH) analog, designed to extend the half-life of GH stimulation compared to its non-DAC counterpart.',
  'Long-acting growth hormone-releasing hormone (GHRH) analog, designed to extend the half-life of GH stimulation via albumin binding.',
  '7-8 days',
  'Store in refrigerator (2-8°C)',
  '["Sustained GH/IGF-1 increase for muscle growth and fat loss", "Improves recovery, sleep, and metabolism", "Long-term anabolic effects"]'::jsonb,
  '["Injection site reactions, water retention", "Headaches, flushing, mild hypoglycemia"]'::jsonb,
  '["Active malignancy, hypersensitivity, pituitary disorders"]'::jsonb,
  '[{"vialSize": "5MG", "reconstitution": "Mix with 1.25mL (125 units) BAC water", "frequency": "Dose once or twice weekly subcutaneously", "subcutaneous": "1-2mg (25-50 units) once or twice weekly"}]'::jsonb,
  '["Ipamorelin: Synergistic GH pulse", "Tesamorelin: Fat reduction", "BPC-157: Tissue repair support"]'::jsonb,
  '🩹'
);

-- Anti-Aging & Longevity Peptides
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon) VALUES
(
  'GHK-Cu',
  '50mg, 100mg, 200mg',
  'Various',
  'Anti-Aging',
  'A copper-binding peptide found in human plasma, researched for anti-aging and regeneration properties.',
  'Copper-binding peptide found in human plasma. Binds copper to stimulate collagen/elastin, reduce oxidative stress, and promote healing.',
  '2-4 hours',
  'Store in refrigerator (2-8°C)',
  '["Wound healing, collagen production", "Anti-inflammatory, skin elasticity improvement", "Tissue remodeling"]'::jsonb,
  '["Injection pain, copper sensitivity"]'::jsonb,
  '["Copper allergy"]'::jsonb,
  '[{"vialSize": "50MG", "reconstitution": "Mix with 5mL (500 units) BAC water", "frequency": "Dose daily subcutaneously or topical", "subcutaneous": "1-2mg (10-20 units) daily subcutaneously or topical"}]'::jsonb,
  '["BPC-157/TB-500: Repair synergy", "Glow blend: Anti-aging"]'::jsonb,
  '✨'
),
(
  'Epitalon',
  '10mg, 50mg',
  'Various',
  'Anti-Aging',
  'A synthetic tetrapeptide that activates telomerase for longevity research and cellular health.',
  'Synthetic tetrapeptide that activates telomerase for longevity research. Stimulates telomerase to elongate telomeres, enhancing cellular longevity.',
  '30 minutes',
  'Store in refrigerator (2-8°C)',
  '["Telomere lengthening", "Antioxidant defense, anti-aging effects"]'::jsonb,
  '["Minimal reported"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL BAC water", "frequency": "Dose daily subcutaneously for 10-20 days, cycle 2x/year", "subcutaneous": "5-10mg daily subcutaneously for 10-20 days, cycle 2x/year"}, {"vialSize": "50MG", "reconstitution": "Mix with 10mL BAC water", "frequency": "Dose daily subcutaneously for 10-20 days, cycle 2x/year", "subcutaneous": "5-10mg (1-2 units) daily"}]'::jsonb,
  '["GHK-Cu: Anti-aging synergy", "NAD+: Cellular energy"]'::jsonb,
  '✨'
),
(
  'NAD+',
  '100mg, 500mg',
  'Various',
  'Anti-Aging',
  'A coenzyme for cellular energy and DNA repair in anti-aging research, essential for mitochondrial function.',
  'Coenzyme for cellular energy and DNA repair in anti-aging research. Boosts sirtuins and mitochondrial function for longevity pathways.',
  '1-2 hours',
  'Store in refrigerator (2-8°C)',
  '["Enhances energy, DNA repair", "Anti-aging, metabolic support"]'::jsonb,
  '["Flushing, nausea at high doses"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "100MG", "reconstitution": "Mix with 10mL saline for IV or 1mL BAC for subcutaneous", "frequency": "Dose 1-3x/week IV/subcutaneous", "subcutaneous": "100-500mg 1-3x/week IV/subcutaneous"}]'::jsonb,
  '["Glutathione: Antioxidant synergy", "Epitalon: Longevity"]'::jsonb,
  '✨'
),
(
  'Glutathione',
  '600mg, 1500mg',
  'Various',
  'Anti-Aging',
  'A tripeptide antioxidant for detoxification and cellular protection.',
  'Scavenges ROS, supports liver detox, enhances immune function.',
  '1-2 hours',
  'Store in refrigerator (2-8°C)',
  '["Reduces oxidative stress", "Supports detox and immunity", "Anti-aging effects"]'::jsonb,
  '["Mild injection reactions"]'::jsonb,
  '["Hypersensitivity to components"]'::jsonb,
  '[{"vialSize": "600MG", "reconstitution": "Mix with 6mL saline for IV", "frequency": "Dose 600mg IV 1-3x/week", "subcutaneous": "600mg IV 1-3x/week"}]'::jsonb,
  '["NAD+: Cellular repair", "BPC-157: Protection"]'::jsonb,
  '✨'
);

-- Cognitive Enhancement & Neuroprotection
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon) VALUES
(
  'Semax',
  '5mg, 10mg, 30mg',
  'Various',
  'Cognitive Enhancement',
  'An ACTH analog for neuroprotection and cognition enhancement, researched for its neuroprotective properties.',
  'ACTH analog for neuroprotection and cognition. Upregulates BDNF/NGF, enhances dopamine/serotonin.',
  '20-30 minutes',
  'Store in refrigerator (2-8°C)',
  '["Improves memory, learning", "Stress resilience, neuroprotection"]'::jsonb,
  '["Nasal irritation"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "30MG (NASAL)", "reconstitution": "Mix for nasal spray", "frequency": "Dose daily intranasal", "subcutaneous": "200-600mcg/day intranasal"}]'::jsonb,
  '["Selank: Mood/cognition", "Cerebrolysin: Brain repair"]'::jsonb,
  '🧠'
),
(
  'Selank',
  '5mg, 10mg',
  'Various',
  'Cognitive Enhancement',
  'A synthetic tuftsin analog for anxiety and cognitive enhancement, researched for its anxiolytic properties.',
  'Synthetic tuftsin analog for anxiety and cognitive enhancement. Modulates GABA/serotonin, enhances BDNF.',
  '30-40 minutes',
  'Store in refrigerator (2-8°C)',
  '["Reduces anxiety without sedation", "Improves cognition, stress resilience"]'::jsonb,
  '["Nasal irritation (intranasal)"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL for nasal spray or BAC for subcutaneous", "frequency": "Dose daily intranasal or subcutaneous", "subcutaneous": "200-600mcg/day intranasal or subcutaneous"}]'::jsonb,
  '["Semax: Cognitive synergy", "Cerebrolysin: Neuroprotection"]'::jsonb,
  '🧠'
),
(
  'Cerebrolysin',
  '30mg, 60mg',
  'Various',
  'Cognitive Enhancement',
  'A neurotrophic mixture from porcine brain for neuroprotection.',
  'Promotes neuronal survival, BDNF expression.',
  '4-6 hours',
  'Store in refrigerator (2-8°C)',
  '["Brain repair, cognitive enhancement", "Neurological recovery"]'::jsonb,
  '["Injection reactions"]'::jsonb,
  '["Epilepsy, renal impairment"]'::jsonb,
  '[{"vialSize": "30MG", "reconstitution": "Dilute in saline for IM/IV", "frequency": "Dose 5-10mL daily IM/IV for 10-20 days", "subcutaneous": "5-10mL daily IM/IV for 10-20 days"}]'::jsonb,
  '["Semax/Selank: Cognitive"]'::jsonb,
  '🧠'
);

-- Sexual Health & Reproductive Peptides
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon) VALUES
(
  'PT-141',
  '10mg',
  'Various',
  'Sexual Health',
  'A melanocortin agonist for sexual dysfunction research.',
  'Activates MC4R in the CNS to enhance arousal and libido.',
  '2-3 hours',
  'Store in refrigerator (2-8°C)',
  '["Improves sexual desire and performance", "Potential for erectile dysfunction"]'::jsonb,
  '["Nausea, flushing, headache", "Hyperpigmentation with chronic use"]'::jsonb,
  '["Cardiovascular disease, pregnancy"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL BAC water", "frequency": "Dose 1-2mg (10-20 units) subcutaneously as needed, 45 min before activity", "subcutaneous": "1-2mg (10-20 units) subcutaneously as needed, 45 min before activity"}]'::jsonb,
  '["Melanotan 2: Libido enhancement", "Kisspeptin: Reproductive support"]'::jsonb,
  '❤️'
),
(
  'HCG',
  '5000iu, 10000iu',
  'Various',
  'Sexual Health',
  'A glycoprotein hormone mimicking LH for fertility and hormone research.',
  'Stimulates Leydig cells for testosterone production and gonadal function.',
  '24-36 hours',
  'Store in refrigerator (2-8°C)',
  '["Maintains testicular function in cycles", "Supports fertility and hormone balance"]'::jsonb,
  '["Gynecomastia, water retention", "Injection site pain"]'::jsonb,
  '["Prostate issues, hypersensitivity"]'::jsonb,
  '[{"vialSize": "5000IU", "reconstitution": "Mix with 5mL BAC water", "frequency": "Dose 500-2000IU 2-3x/week subcutaneously or IM", "subcutaneous": "500-2000IU 2-3x/week subcutaneously or IM"}]'::jsonb,
  '["Kisspeptin: Reproductive synergy", "Tesamorelin: Hormonal balance"]'::jsonb,
  '❤️'
),
(
  'Kisspeptin-10',
  '10mg',
  'Various',
  'Sexual Health',
  'A neuropeptide for GnRH regulation and fertility research.',
  'Stimulates GnRH release, increasing LH/FSH.',
  '4-5 minutes',
  'Store in refrigerator (2-8°C)',
  '["Enhances testosterone, fertility", "Reproductive hormone support"]'::jsonb,
  '["Mild hormonal fluctuations"]'::jsonb,
  '["Pregnancy, hypersensitivity"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL BAC water", "frequency": "Dose 10-100mcg daily subcutaneously", "subcutaneous": "10-100mcg daily subcutaneously"}]'::jsonb,
  '["HCG: Gonadal stimulation"]'::jsonb,
  '❤️'
),
(
  'Oxytocin',
  '2mg',
  'Various',
  'Social & Emotional',
  'A neuropeptide for social bonding and reproductive research.',
  'Binds oxytocin receptors for trust, labor induction.',
  '3-4 minutes',
  'Store in refrigerator (2-8°C)',
  '["Enhances social cognition", "Supports fertility, mood"]'::jsonb,
  '["Nausea, headache"]'::jsonb,
  '["Pregnancy complications"]'::jsonb,
  '[{"vialSize": "2MG", "reconstitution": "Mix with 2mL BAC water", "frequency": "Dose 10-40IU (5-20 units) intranasal daily", "subcutaneous": "10-40IU (5-20 units) intranasal daily"}]'::jsonb,
  '["Kisspeptin: Reproductive", "PT-141: Libido"]'::jsonb,
  '❤️'
);

-- Sleep & Recovery Peptides
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon) VALUES
(
  'DSIP',
  '5mg, 15mg',
  'Various',
  'Sleep & Recovery',
  'A neuropeptide for sleep regulation and stress reduction research.',
  'Modulates GABA and sleep-wake cycles.',
  '30 minutes',
  'Store in refrigerator (2-8°C)',
  '["Improves sleep quality", "Reduces stress, chronic pain"]'::jsonb,
  '["Mild headache"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "5MG", "reconstitution": "Mix with 1mL BAC water", "frequency": "Dose 100-1000mcg before bed subcutaneously", "subcutaneous": "100-1000mcg before bed subcutaneously"}]'::jsonb,
  '["Selank: Anxiety reduction"]'::jsonb,
  '🧠'
),
(
  'Melatonin',
  '5mg',
  'Various',
  'Sleep & Recovery',
  'A hormone peptide for sleep and antioxidant research.',
  'Binds MT1/MT2 receptors for circadian regulation.',
  '30-60 minutes',
  'Store in refrigerator (2-8°C)',
  '["Improves sleep, antioxidant protection", "Anti-aging"]'::jsonb,
  '["Drowsiness, headache"]'::jsonb,
  '["Autoimmune diseases"]'::jsonb,
  '[{"vialSize": "STANDARD", "reconstitution": "Oral 0.5-5mg nightly; peptide form subcutaneous 1-3mg", "frequency": "Oral 0.5-5mg nightly; peptide form subcutaneous 1-3mg", "subcutaneous": "Oral 0.5-5mg nightly; peptide form subcutaneous 1-3mg"}]'::jsonb,
  '["DSIP: Sleep enhancement"]'::jsonb,
  '🔬'
);

-- Peptide Combinations
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon) VALUES
(
  'BPC 5mg + TB 5mg',
  '10mg',
  'Various',
  'Peptide Combinations',
  'A combination of BPC-157 and TB-500 for comprehensive tissue repair.',
  'Combined healing effects of both peptides for enhanced repair.',
  '4-6 hours',
  'Store in refrigerator (2-8°C)',
  '["Accelerated healing", "Enhanced tissue repair", "Reduced inflammation"]'::jsonb,
  '["Minimal injection site reactions"]'::jsonb,
  '["Hypersensitivity to either component"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL BAC water", "frequency": "Dose daily subcutaneously", "subcutaneous": "250-500mcg daily"}]'::jsonb,
  '["GHK-Cu: Enhanced collagen synthesis"]'::jsonb,
  '🩹'
),
(
  'GLOW (BPC-157 + GHK-Cu + TB500)',
  '70mg, 80mg',
  'Various',
  'Peptide Combinations',
  'A blend of 50mg GHK-Cu, 10mg BPC-157, and 10mg TB-500 for anti-aging and skin rejuvenation.',
  'GHK-Cu: Collagen production. BPC-157/TB-500: Repair and angiogenesis.',
  '4-6 hours',
  'Store in refrigerator (2-8°C)',
  '["Improves skin elasticity and hydration", "Reverses thinning, stimulates elastin"]'::jsonb,
  '["Copper sensitivity reactions"]'::jsonb,
  '["Copper allergy"]'::jsonb,
  '[{"vialSize": "70MG", "reconstitution": "Mix with 3mL (300 units) BAC water", "frequency": "Dose 7 days/week subcutaneously, 6 weeks on/6 off; dilute with 20-30 units BAC", "subcutaneous": "7 days/week subcutaneously, 6 weeks on/6 off; dilute with 20-30 units BAC"}]'::jsonb,
  '["Epitalon: Telomere support", "NAD+: Energy enhancement"]'::jsonb,
  '✨'
),
(
  'KLOW (Multi-Peptide Repair Blend)',
  '80mg',
  'Various',
  'Peptide Combinations',
  'A blend of 50mg GHK-Cu, 10mg TB-500, 10mg BPC-157, and 10mg KPV for comprehensive repair.',
  'GHK-Cu/TB-500/BPC-157: Tissue repair and angiogenesis. KPV: Anti-inflammatory.',
  '4-6 hours',
  'Store in refrigerator (2-8°C)',
  '["Inflammation control, collagen synthesis", "Skin/hair quality, GI integrity", "Broad repair"]'::jsonb,
  '["Injection site reactions"]'::jsonb,
  '["Copper sensitivity"]'::jsonb,
  '[{"vialSize": "80MG", "reconstitution": "Mix with 4mL (400 units) BAC water", "frequency": "Dose 8-10 units daily subcutaneously, 6 weeks on/6 off", "subcutaneous": "8-10 units daily subcutaneously, 6 weeks on/6 off"}]'::jsonb,
  '["NAD+: Cellular repair", "Selank: Cognitive recovery"]'::jsonb,
  '🩹'
),
(
  'Cagrilintide + Semaglutide',
  '5mg/5mg, 10mg/10mg',
  'Various',
  'Peptide Combinations',
  'A combined GLP-1/amylin analog for weight loss.',
  'Semaglutide: Suppresses appetite via GLP-1. Cagrilintide: Enhances satiety via amylin.',
  '7 days',
  'Store in refrigerator (2-8°C)',
  '["Enhanced weight loss (up to 15-20% in trials)", "Improved glycemic control"]'::jsonb,
  '["Nausea, GI upset"]'::jsonb,
  '["Pregnancy, hypersensitivity"]'::jsonb,
  '[{"vialSize": "5MG/5MG", "reconstitution": "Mix with 2mL BAC water", "frequency": "Dose 1-2mg weekly subcutaneous, titrate over 4 weeks", "subcutaneous": "1-2mg weekly subcutaneous, titrate over 4 weeks"}]'::jsonb,
  '["AOD-9604: Fat loss", "BPC-157: GI support"]'::jsonb,
  '💊'
);

-- Immune Support Peptides
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon) VALUES
(
  'Thymosin Alpha-1',
  '5mg, 10mg',
  'Various',
  'Immune Support',
  'A thymic peptide for immune modulation.',
  'Enhances T-cell function, cytokine production.',
  '2-4 hours',
  'Store in refrigerator (2-8°C)',
  '["Immune enhancement, antiviral activity", "Cancer and infection support"]'::jsonb,
  '["Mild flu-like symptoms"]'::jsonb,
  '["Autoimmune disease"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL BAC water", "frequency": "Dose 1.6mg (3.2 units) 2x/week", "subcutaneous": "1.6mg (3.2 units) 2x/week"}]'::jsonb,
  '["Glutathione: Immune support"]'::jsonb,
  '🔬'
),
(
  'Thymalin',
  '10mg',
  'Various',
  'Immune Support',
  'A thymic extract peptide for immune modulation.',
  'Enhances T-cell maturation and immune balance.',
  '2-4 hours',
  'Store in refrigerator (2-8°C)',
  '["Boosts immunity, anti-aging", "Reduces inflammation"]'::jsonb,
  '["Minimal"]'::jsonb,
  '["Autoimmune disorders"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL BAC water", "frequency": "Dose 5-10mg daily for 10 days, cycle quarterly", "subcutaneous": "5-10mg daily for 10 days, cycle quarterly"}]'::jsonb,
  '["Thymosin Alpha-1: Immune synergy"]'::jsonb,
  '🔬'
);

-- Additional Advanced Peptides
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon) VALUES
(
  'AOD-9604',
  '5mg',
  'Various',
  'Weight Management',
  'A fragment of human growth hormone designed for obesity research, targeting fat metabolism without affecting blood sugar.',
  'Fragment of human growth hormone designed for obesity research, targeting fat metabolism without affecting blood sugar. Mimics HGH''s fat-burning portion to promote lipolysis and inhibit lipogenesis.',
  '2-4 hours',
  'Store in refrigerator (2-8°C)',
  '["Promotes fat metabolism", "Preserves lean muscle", "No impact on blood glucose"]'::jsonb,
  '["Mild injection site reactions"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "5MG", "reconstitution": "Mix with 1mL (100 units) BAC water", "frequency": "Dose daily subcutaneously, 5 days/week with 2 rest days", "subcutaneous": "300mcg (3 units) daily subcutaneously, 5 days/week with 2 rest days. Inject post-wakeup; fast 1 hour after"}]'::jsonb,
  '["Tirzepatide/Semaglutide: Enhanced fat loss", "BPC-157: GI support"]'::jsonb,
  '💊'
),
(
  'Melanotan-2',
  '5mg, 10mg',
  'Various',
  'Melanotan',
  'A synthetic analog of alpha-melanocyte-stimulating hormone (α-MSH), researched for skin tanning and potential libido enhancement.',
  'Synthetic analog of alpha-melanocyte-stimulating hormone (α-MSH), researched for skin tanning and potential libido enhancement via melanocortin receptor activation.',
  '2-3 hours',
  'Store in refrigerator (2-8°C)',
  '["Promotes skin pigmentation for UV protection", "Enhances libido and erectile function in research models", "Potential appetite suppression"]'::jsonb,
  '["Nausea, flushing, spontaneous erections", "Increased moles or freckles", "Rare: Priapism, renal effects"]'::jsonb,
  '["Avoid in pregnancy or hypersensitivity", "Not for those with skin cancer history"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL (200 units) BAC water", "frequency": "Dose subcutaneously, start low for tolerance", "subcutaneous": "5 units = 0.25mg; 10 units = 0.5mg (loading: 0.25mg/day for 1-2 weeks; maintenance: 0.5mg 2-3x/week)"}]'::jsonb,
  '["PT-141: Synergistic for libido", "BPC-157: For any injection site irritation"]'::jsonb,
  '🔬'
),
(
  'Mazdutide',
  '9mg',
  'Various',
  'Weight Management',
  'A dual agonist of the GLP-1 and glucagon receptors, originally designed to treat type 2 diabetes and obesity with minimal side effects.',
  'GLP-1: Suppresses appetite, enhances satiety. Glucagon: Boosts energy expenditure and fat oxidation.',
  '5-7 days',
  'Store in refrigerator (2-8°C)',
  '["Significant weight loss and calorie burning", "Improves glycemic control", "Metabolic boost with low GI impact"]'::jsonb,
  '["Mild nausea, GI upset", "Injection site reactions"]'::jsonb,
  '["Pregnancy, hypersensitivity, severe GI disease"]'::jsonb,
  '[{"vialSize": "9MG", "reconstitution": "Mix with 1.8mL (180 units) BAC water", "frequency": "Dose weekly subcutaneously, minimum 4 weeks per level", "subcutaneous": "20 units = 1mg; 30 units = 1.5mg; 45 units = 2.25mg; 60 units = 3mg; 90 units = 4.5mg; 120 units = 6mg; 180 units = 9mg"}]'::jsonb,
  '["AOD-9604: Enhances fat breakdown", "BPC-157: GI support"]'::jsonb,
  '💊'
),
(
  'Cagrilintide',
  '5mg, 10mg',
  'Various',
  'Weight Management',
  'A long-acting amylin analog peptide for appetite suppression and weight management, often combined with GLP-1 agonists.',
  'Mimics amylin to slow gastric emptying, reduce appetite, and enhance satiety signaling in the brain.',
  '6-8 days',
  'Store in refrigerator (2-8°C)',
  '["Amplifies weight loss (up to 10.8% in 26 weeks)", "Reduces food intake and supports sustained management", "Improves glycemic balance when stacked"]'::jsonb,
  '["Nausea, bloating, injection site reactions", "Constipation or mild GI discomfort"]'::jsonb,
  '["Severe GI disease, pregnancy, hypersensitivity"]'::jsonb,
  '[{"vialSize": "5MG", "reconstitution": "Mix with 1mL (100 units) BAC water", "frequency": "Dose weekly subcutaneously, titrate slowly", "subcutaneous": "20 units = 1mg; 40 units = 2mg; 60 units = 3mg; 80 units = 4mg; 100 units = 5mg"}]'::jsonb,
  '["Semaglutide/Tirzepatide: Synergistic weight loss (CagriSema combo)", "BPC-157: Mitigates GI effects"]'::jsonb,
  '💊'
),
(
  'MOTS-c',
  '10mg, 40mg',
  'Various',
  'Anti-Aging',
  'A mitochondrial-derived peptide for metabolic regulation.',
  'Regulates nuclear genes for energy homeostasis.',
  '30 minutes',
  'Store in refrigerator (2-8°C)',
  '["Improves insulin sensitivity, exercise capacity", "Fat loss, longevity"]'::jsonb,
  '["Minimal"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "15MG", "reconstitution": "Mix with 3mL BAC water", "frequency": "Dose 5-10mg weekly subcutaneously", "subcutaneous": "5-10mg weekly subcutaneously"}]'::jsonb,
  '["NAD+: Mitochondrial", "Tirzepatide: Metabolic"]'::jsonb,
  '✨'
);

-- More growth hormone peptides
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon) VALUES
(
  'CJC-1295 NO dac',
  '5mg, 10mg',
  'Various',
  'Growth Hormone',
  'A GHRH analog for GH stimulation without a drug affinity complex.',
  'Binds GHRH receptors to pulse GH release.',
  '30 minutes',
  'Store in refrigerator (2-8°C)',
  '["Increases GH/IGF-1 for growth and recovery", "Improves sleep and metabolism"]'::jsonb,
  '["Injection site reactions, water retention"]'::jsonb,
  '["Active malignancy, hypersensitivity"]'::jsonb,
  '[{"vialSize": "5MG", "reconstitution": "Mix with 1mL BAC water", "frequency": "Dose 100-300mcg (2-6 units) 1-2x daily", "subcutaneous": "100-300mcg (2-6 units) 1-2x daily"}]'::jsonb,
  '["Ipamorelin: GH synergy", "Tesamorelin: Fat loss"]'::jsonb,
  '🩹'
),
(
  'GHRP-6 Acetate',
  '5mg, 10mg',
  'Various',
  'Growth Hormone',
  'A growth hormone-releasing peptide with appetite stimulation.',
  'Activates ghrelin receptors for GH release.',
  '2-3 hours',
  'Store in refrigerator (2-8°C)',
  '["Increases GH, appetite, and muscle mass", "Improves recovery"]'::jsonb,
  '["Hunger, water retention"]'::jsonb,
  '["Active malignancy, hypersensitivity"]'::jsonb,
  '[{"vialSize": "5MG", "reconstitution": "Mix with 1mL BAC water", "frequency": "Dose 100-300mcg (2-6 units) 1-2x daily subcutaneously", "subcutaneous": "100-300mcg (2-6 units) 1-2x daily subcutaneously"}]'::jsonb,
  '["CJC-1295: GH boost", "Ipamorelin: Synergy"]'::jsonb,
  '🩹'
),
(
  'Sermorelin Acetate',
  '5mg, 10mg, 15mg',
  'Various',
  'Growth Hormone',
  'A GHRH analog for stimulating endogenous GH release.',
  'Binds pituitary GHRH receptors to pulse GH secretion.',
  '15-30 minutes',
  'Store in refrigerator (2-8°C)',
  '["Boosts energy, metabolism, lean muscle", "Reduces fatigue, improves sleep"]'::jsonb,
  '["Injection site reactions, flushing"]'::jsonb,
  '["Pituitary disorders, hypersensitivity"]'::jsonb,
  '[{"vialSize": "5MG", "reconstitution": "Mix with 1mL BAC water", "frequency": "Dose 200-500mcg (4-10 units) nightly", "subcutaneous": "200-500mcg (4-10 units) nightly"}]'::jsonb,
  '["Ipamorelin: GH synergy", "BPC-157: Recovery"]'::jsonb,
  '🩹'
),
(
  'Tesamorelin',
  '5mg, 10mg',
  'Various',
  'Growth Hormone',
  'A GHRH analog for reducing visceral fat in lipodystrophy research.',
  'Stimulates pituitary GH release, increasing IGF-1 for fat metabolism.',
  '26 minutes',
  'Store in refrigerator (2-8°C)',
  '["Reduces visceral fat, improves lipids", "Enhances metabolic regulation"]'::jsonb,
  '["Injection reactions, joint pain"]'::jsonb,
  '["Malignancy, hypersensitivity"]'::jsonb,
  '[{"vialSize": "5MG", "reconstitution": "Mix with 1mL BAC water", "frequency": "Dose 2mg (40 units) daily", "subcutaneous": "2mg (40 units) daily"}]'::jsonb,
  '["Ipamorelin: GH enhancement", "Tirzepatide: Fat loss"]'::jsonb,
  '🩹'
),
(
  'HGH 191AA (Somatropin)',
  '10iu, 15iu',
  'Various',
  'Growth Hormone',
  'A recombinant human growth hormone for growth and metabolic research.',
  'Binds GH receptors to promote IGF-1 production, cell growth, and metabolism.',
  '2-3 hours',
  'Store in refrigerator (2-8°C)',
  '["Increases lean mass, reduces fat", "Improves recovery, bone density"]'::jsonb,
  '["Edema, carpal tunnel, insulin resistance"]'::jsonb,
  '["Active cancer, diabetes complications"]'::jsonb,
  '[{"vialSize": "10IU", "reconstitution": "Reconstitute per vial instructions", "frequency": "Dose 2-4IU daily subcutaneously", "subcutaneous": "2-4IU daily subcutaneously"}]'::jsonb,
  '["CJC-1295: Endogenous GH boost", "Ipamorelin: Synergy"]'::jsonb,
  '🩹'
),
(
  'IGF-1 LR3',
  '0.1mg, 1mg',
  'Various',
  'Growth Hormone',
  'A long-acting insulin-like growth factor for muscle growth and repair.',
  'Binds IGF-1 receptors to promote protein synthesis and cell growth.',
  '20-30 hours',
  'Store in refrigerator (2-8°C)',
  '["Enhances muscle hypertrophy and recovery", "Improves tissue repair"]'::jsonb,
  '["Hypoglycemia, joint pain"]'::jsonb,
  '["Active cancer, hypersensitivity"]'::jsonb,
  '[{"vialSize": "1MG", "reconstitution": "Mix with 1mL BAC water", "frequency": "Dose 20-100mcg daily subcutaneous, post-workout", "subcutaneous": "20-100mcg daily subcutaneous, post-workout"}]'::jsonb,
  '["CJC-1295: GH synergy", "BPC-157: Repair"]'::jsonb,
  '🩹'
),
(
  'IGF-1 DES',
  '1mg, 2mg',
  'Various',
  'Growth Hormone',
  'A short-acting variant of IGF-1 for localized muscle growth.',
  'Targets muscle cells directly for anabolic effects.',
  '20 minutes',
  'Store in refrigerator (2-8°C)',
  '["Localized muscle growth and repair", "Enhanced recovery"]'::jsonb,
  '["Hypoglycemia, injection site reactions"]'::jsonb,
  '["Active cancer, hypersensitivity"]'::jsonb,
  '[{"vialSize": "1MG", "reconstitution": "Mix with 1mL BAC water", "frequency": "Dose 50-150mcg per muscle group post-workout", "subcutaneous": "50-150mcg per muscle group post-workout"}]'::jsonb,
  '["IGF-1 LR3: Systemic support", "Ipamorelin: GH boost"]'::jsonb,
  '🩹'
),
(
  'Hexarelin Acetate',
  '5mg',
  'Various',
  'Growth Hormone',
  'A hexapeptide growth hormone secretagogue.',
  'Stimulates GH release via ghrelin receptors.',
  '2-3 hours',
  'Store in refrigerator (2-8°C)',
  '["Increases GH for growth and recovery", "Improves strength and metabolism"]'::jsonb,
  '["Water retention, tingling"]'::jsonb,
  '["Active malignancy, hypersensitivity"]'::jsonb,
  '[{"vialSize": "2MG", "reconstitution": "Mix with 0.4mL BAC water", "frequency": "Dose 100-300mcg (5-15 units) 1-2x daily subcutaneously", "subcutaneous": "100-300mcg (5-15 units) 1-2x daily subcutaneously"}]'::jsonb,
  '["CJC-1295: GH synergy", "BPC-157: Recovery"]'::jsonb,
  '🩹'
),
(
  'HGH Fragment 176-191',
  '5mg',
  'Various',
  'Weight Management',
  'A modified HGH peptide for fat loss without growth effects.',
  'Stimulates lipolysis and inhibits lipogenesis in adipose tissue.',
  '30 minutes',
  'Store in refrigerator (2-8°C)',
  '["Targeted fat reduction", "Preserves muscle"]'::jsonb,
  '["Mild head rush, injection pain"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "5MG", "reconstitution": "Mix with 2mL BAC water", "frequency": "Dose 250-500mcg daily subcutaneously before cardio", "subcutaneous": "250-500mcg daily subcutaneously before cardio"}]'::jsonb,
  '["AOD-9604: Lipolytic synergy", "Tirzepatide: Weight loss"]'::jsonb,
  '💊'
);

-- Additional specialized peptides
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon) VALUES
(
  '5-Amino-1MQ',
  '5mg, 10mg',
  'Various',
  'Weight Management',
  'A small molecule NNMT inhibitor to boost metabolism and NAD+ levels.',
  'Inhibits NNMT to increase NAD+, enhancing fat oxidation and mitochondrial function.',
  '2-4 hours',
  'Store in refrigerator (2-8°C)',
  '["Fat loss and muscle preservation", "Metabolic efficiency", "Energy expenditure increase"]'::jsonb,
  '["Mild GI upset"]'::jsonb,
  '["Pregnancy, cardiovascular/liver/kidney issues, hypersensitivity"]'::jsonb,
  '[{"vialSize": "50MG", "reconstitution": "Oral capsules or mix with 1mL BAC water for subcutaneous", "frequency": "Dose 50-150mg/day, 8-12 week cycles", "subcutaneous": "50-150mg/day oral or subcutaneous"}]'::jsonb,
  '["Tirzepatide: Fat loss synergy", "NAD+: Metabolic boost"]'::jsonb,
  '💊'
),
(
  'Adipotide',
  '2mg, 5mg, 10mg',
  'Various',
  'Weight Management',
  'A peptidomimetic that targets white fat cells for obesity research.',
  'Binds to prohibitin on blood vessels supplying white adipose tissue, inducing apoptosis.',
  '2-3 hours',
  'Store in refrigerator (2-8°C)',
  '["Selective white fat reduction", "Potential for rapid weight loss in models"]'::jsonb,
  '["Kidney toxicity, dehydration", "Injection site pain"]'::jsonb,
  '["Renal impairment, pregnancy"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL BAC water", "frequency": "Dose 0.25mg/kg 5 days/week subcutaneously", "subcutaneous": "0.25mg/kg 5 days/week subcutaneously"}]'::jsonb,
  '["AOD-9604: Fat targeting", "BPC-157: Organ protection"]'::jsonb,
  '💊'
),
(
  'Survodutide',
  '10mg',
  'Various',
  'Weight Management',
  'A dual GLP-1/glucagon agonist for diabetes and obesity research, similar to Mazdutide.',
  'GLP-1: Reduces appetite, enhances satiety. Glucagon: Promotes fat oxidation and energy expenditure.',
  '5-6 days',
  'Store in refrigerator (2-8°C)',
  '["Weight management and glycemic control", "Enhances metabolic rate", "Liver fat reduction"]'::jsonb,
  '["Nausea, vomiting, injection site reactions"]'::jsonb,
  '["Pregnancy, hypersensitivity, severe GI issues"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL (200 units) BAC water", "frequency": "Start at 24 units (1.2mg) weekly; stay 4 weeks before increasing", "subcutaneous": "24 units = 1.2mg; 48 units = 2.4mg; 72 units = 3.6mg; 96 units = 4.8mg; 120 units = 6mg; 200 units = 10mg"}]'::jsonb,
  '["AOD-9604: Fat loss synergy", "BPC-157: GI health"]'::jsonb,
  '💊'
),
(
  'Lemon Bottle',
  '10mg',
  'Various',
  'Accessories & Supplies',
  'A proprietary fat-dissolving solution with riboflavin, lecithin, and bromelain for targeted fat elimination.',
  'Disrupts adipocyte membranes to release and metabolize fat locally.',
  'N/A',
  'Store in refrigerator (2-8°C)',
  '["Non-surgical fat reduction in targeted areas", "Body contouring"]'::jsonb,
  '["Swelling, bruising, mild discomfort"]'::jsonb,
  '["Hypersensitivity to ingredients"]'::jsonb,
  '[{"vialSize": "STANDARD VIAL", "reconstitution": "No reconstitution needed; inject 0.2-0.5mL per site, 1-3 sessions spaced 1 week apart", "frequency": "1-3 sessions spaced 1 week apart", "subcutaneous": "Inject 0.2-0.5mL per site"}]'::jsonb,
  '["Tirzepatide: Overall fat loss enhancement"]'::jsonb,
  '💊'
),
(
  'Lipo-C with Vitamins B12',
  '10mg',
  'Various',
  'Accessories & Supplies',
  'A blend of methionine, inositol, choline, L-carnitine, and B vitamins for fat metabolism research.',
  'Lipotropics aid fat transport and breakdown. Carnitine shuttles fatty acids to mitochondria.',
  'N/A',
  'Store in refrigerator (2-8°C)',
  '["Supports fat metabolism and energy", "Detoxification and vascular function"]'::jsonb,
  '["Mild GI upset, injection pain"]'::jsonb,
  '["Liver disease, hypersensitivity"]'::jsonb,
  '[{"vialSize": "STANDARD VIAL", "reconstitution": "No reconstitution; dose 1-2mL IM weekly", "frequency": "Dose 1-2mL IM weekly", "subcutaneous": "1-2mL IM weekly"}]'::jsonb,
  '["Retatrutide: Metabolic synergy"]'::jsonb,
  '💊'
),
(
  'L-Carnitine',
  '500mg, 10ml',
  'Various',
  'Muscle & Joint Support',
  'An amino acid derivative for fatty acid transport in energy production.',
  'Transports long-chain fatty acids into mitochondria for β-oxidation.',
  '2-4 hours',
  'Store in refrigerator (2-8°C)',
  '["Enhances fat burning and endurance", "Reduces fatigue, supports recovery"]'::jsonb,
  '["Nausea, diarrhea at high doses"]'::jsonb,
  '["Seizure disorders, hypothyroidism"]'::jsonb,
  '[{"vialSize": "500MG", "reconstitution": "Mix with 5mL BAC water", "frequency": "Dose 500-2000mg daily IM or oral", "subcutaneous": "500-2000mg daily IM or oral"}]'::jsonb,
  '["AOD-9604: Fat loss", "Ipamorelin: Recovery"]'::jsonb,
  '💊'
),
(
  'Snap-8',
  '10mg',
  'Various',
  'Anti-Aging',
  'A synthetic octapeptide mimicking Botox for cosmetic research.',
  'Inhibits acetylcholine release to reduce muscle contractions and wrinkles.',
  '2-4 hours',
  'Store in refrigerator (2-8°C)',
  '["Reduces expression lines", "Skin smoothing"]'::jsonb,
  '["Skin irritation"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix as 0.5% topical cream or with 2mL BAC for injectable", "frequency": "Apply topical daily or inject 0.1mL per site", "subcutaneous": "Apply topical daily or inject 0.1mL per site"}]'::jsonb,
  '["GHK-Cu: Skin rejuvenation", "Glow: Anti-aging"]'::jsonb,
  '✨'
),
(
  'AHK-Cu',
  '50mg, 100mg',
  'Various',
  'Anti-Aging',
  'A copper-binding peptide for hair growth and skin repair.',
  'Promotes collagen and hair follicle activity via copper.',
  '2-4 hours',
  'Store in refrigerator (2-8°C)',
  '["Stimulates hair growth, skin repair", "Anti-aging effects"]'::jsonb,
  '["Copper sensitivity"]'::jsonb,
  '["Copper allergy"]'::jsonb,
  '[{"vialSize": "50MG", "reconstitution": "Mix with 5mL BAC water", "frequency": "Dose 1-2mg daily subcutaneous or topical", "subcutaneous": "1-2mg daily subcutaneous or topical"}]'::jsonb,
  '["GHK-Cu: Skin synergy", "BPC-157: Repair"]'::jsonb,
  '✨'
),
(
  'Pinealon',
  '10mg, 20mg',
  'Various',
  'Anti-Aging',
  'A synthetic tripeptide bioregulator for brain health and longevity.',
  'Regulates gene expression in pineal gland for melatonin and neuroprotection.',
  '1-2 hours',
  'Store in refrigerator (2-8°C)',
  '["Improves cognition, sleep", "Anti-aging brain support"]'::jsonb,
  '["Minimal"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "20MG", "reconstitution": "Mix with 2mL BAC water", "frequency": "Dose 100-200mcg daily subcutaneously for 10 days, cycle monthly", "subcutaneous": "100-200mcg daily subcutaneously for 10 days, cycle monthly"}]'::jsonb,
  '["Epitalon: Longevity", "Semax: Cognitive"]'::jsonb,
  '✨'
),
(
  'SS-31',
  '10mg, 25mg, 50mg',
  'Various',
  'Healing & Recovery',
  'A mitochondrial-targeted tetrapeptide for cellular protection.',
  'Binds cardiolipin to reduce oxidative stress, enhance ATP.',
  '2-3 hours',
  'Store in refrigerator (2-8°C)',
  '["Improves mitochondrial function", "Reduces oxidative damage"]'::jsonb,
  '["Minimal"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "25MG", "reconstitution": "Mix with 5mL BAC water", "frequency": "Dose 0.25-1mg/kg daily subcutaneously", "subcutaneous": "0.25-1mg/kg daily subcutaneously"}]'::jsonb,
  '["NAD+: Mitochondrial support"]'::jsonb,
  '✨'
),
(
  'KPV',
  '5mg, 10mg',
  'Various',
  'Healing & Recovery',
  'An alpha-MSH fragment for anti-inflammatory research.',
  'Reduces NF-kB, antimicrobial effects.',
  '2-3 hours',
  'Store in refrigerator (2-8°C)',
  '["Inflammation control, wound healing"]'::jsonb,
  '["Minimal"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL BAC water", "frequency": "Dose 200-500mcg (4-10 units) daily", "subcutaneous": "200-500mcg (4-10 units) daily"}]'::jsonb,
  '["LL-37: Antimicrobial", "KLOW blend"]'::jsonb,
  '🔬'
),
(
  'LL-37',
  '2mg, 10mg',
  'Various',
  'Healing & Recovery',
  'An antimicrobial peptide for immune defense.',
  'Disrupts bacterial membranes, modulates inflammation.',
  '1-2 hours',
  'Store in refrigerator (2-8°C)',
  '["Antimicrobial, wound healing", "Immune regulation"]'::jsonb,
  '["Cytotoxicity at high doses"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "2MG", "reconstitution": "Mix with 1mL BAC water", "frequency": "Dose 50-100mcg daily topical or subcutaneous", "subcutaneous": "50-100mcg daily topical or subcutaneous"}]'::jsonb,
  '["KPV: Anti-inflammatory"]'::jsonb,
  '🔬'
),
(
  'LC120',
  '10mg',
  'Various',
  'Muscle & Joint Support',
  'A peptide for muscle and joint support.',
  'Supports muscle recovery and joint health.',
  '2-4 hours',
  'Store in refrigerator (2-8°C)',
  '["Muscle recovery", "Joint support"]'::jsonb,
  '["Minimal"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL BAC water", "frequency": "Dose daily subcutaneously", "subcutaneous": "Dose daily subcutaneously"}]'::jsonb,
  '["BPC-157: Comprehensive healing"]'::jsonb,
  '🔬'
),
(
  'Dermorphin',
  '5mg',
  'Various',
  'Muscle & Joint Support',
  'A mu-opioid agonist from frog skin for pain research.',
  'Binds opioid receptors for analgesia.',
  '2-3 hours',
  'Store in refrigerator (2-8°C)',
  '["Potent pain relief"]'::jsonb,
  '["Respiratory depression"]'::jsonb,
  '["Opioid sensitivity"]'::jsonb,
  '[{"vialSize": "5MG", "reconstitution": "Mix with 1mL BAC water", "frequency": "Dose 0.1-0.5mg as needed subcutaneously (research only)", "subcutaneous": "0.1-0.5mg as needed subcutaneously (research only)"}]'::jsonb,
  '["BPC-157: Pain synergy"]'::jsonb,
  '🔬'
),
(
  'GLP-1',
  '5mg',
  'Various',
  'Weight Management',
  'An incretin hormone for glucose regulation.',
  'Enhances insulin, suppresses glucagon.',
  '2 minutes',
  'Store in refrigerator (2-8°C)',
  '["Glycemic control, weight loss"]'::jsonb,
  '["Nausea"]'::jsonb,
  '["Pancreatitis history"]'::jsonb,
  '[{"vialSize": "5MG", "reconstitution": "Mix with 1mL BAC water", "frequency": "Dose 0.6-1.2mg weekly subcutaneously", "subcutaneous": "0.6-1.2mg weekly subcutaneously"}]'::jsonb,
  '["Semaglutide analogs"]'::jsonb,
  '💊'
),
(
  'Vasoactive Intestinal Peptide',
  '5mg, 10mg',
  'Various',
  'Cognitive Enhancement',
  'A neuropeptide for vasodilation and immune modulation.',
  'Relaxes smooth muscle, inhibits inflammation.',
  '2 minutes',
  'Store in refrigerator (2-8°C)',
  '["Improves pulmonary function", "Anti-inflammatory"]'::jsonb,
  '["Flushing, hypotension"]'::jsonb,
  '["Low blood pressure"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL BAC water", "frequency": "Dose 100-200mcg nebulized or subcutaneous daily", "subcutaneous": "100-200mcg nebulized or subcutaneous daily"}]'::jsonb,
  '["BPC-157: GI repair"]'::jsonb,
  '🔬'
),
(
  'PNC 27',
  '5mg, 10mg, 20mg',
  'Various',
  'Immune Support',
  'A synthetic peptide targeting cancer cells.',
  'Binds HDM-2 to induce cancer cell necrosis.',
  '2-3 hours',
  'Store in refrigerator (2-8°C)',
  '["Selective tumor cell killing"]'::jsonb,
  '["Unknown long-term"]'::jsonb,
  '["Not for non-cancer research"]'::jsonb,
  '[{"vialSize": "20MG", "reconstitution": "Mix with 4mL BAC water", "frequency": "Dose 1-5mg daily IV in research", "subcutaneous": "1-5mg daily IV in research"}]'::jsonb,
  '["Thymosin Alpha-1: Immune"]'::jsonb,
  '🔬'
),
(
  'SLU-PP-332',
  '5mg',
  'Various',
  'Cognitive Enhancement',
  'An ERR agonist for metabolic research.',
  'Activates estrogen-related receptors for energy expenditure.',
  '2-4 hours',
  'Store in refrigerator (2-8°C)',
  '["Mimics exercise effects, fat loss"]'::jsonb,
  '["Unknown"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "STANDARD", "reconstitution": "Dose per emerging protocols, oral 100-300mg daily", "frequency": "Dose per emerging protocols, oral 100-300mg daily", "subcutaneous": "Dose per emerging protocols, oral 100-300mg daily"}]'::jsonb,
  '["Retatrutide: Metabolic"]'::jsonb,
  '💊'
),
(
  'Ara-290',
  '10mg',
  'Various',
  'Healing & Recovery',
  'An EPO-derived peptide for neuropathy.',
  'Activates EPO receptors for tissue protection.',
  '2-3 hours',
  'Store in refrigerator (2-8°C)',
  '["Neuropathic pain relief, metabolic control"]'::jsonb,
  '["Mild injection reactions"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL BAC water", "frequency": "Dose 2mg daily subcutaneously", "subcutaneous": "2mg daily subcutaneously"}]'::jsonb,
  '["BPC-157: Nerve repair"]'::jsonb,
  '🔬'
),
(
  'Hyaluronic acid',
  '5mg',
  'Various',
  'Accessories & Supplies',
  'A glycosaminoglycan for skin hydration and joint support.',
  'Retains water for tissue lubrication.',
  'N/A',
  'Store in refrigerator (2-8°C)',
  '["Skin hydration, joint lubrication"]'::jsonb,
  '["Minimal"]'::jsonb,
  '["Hypersensitivity"]'::jsonb,
  '[{"vialSize": "5MG", "reconstitution": "Mix for topical or injectable", "frequency": "Dose as needed", "subcutaneous": "Dose as needed"}]'::jsonb,
  '["GHK-Cu: Skin synergy"]'::jsonb,
  '🔬'
),
(
  'HMG',
  '75iu',
  'Various',
  'Sexual Health',
  'Human menopausal gonadotropin for fertility research.',
  'Contains FSH/LH for ovarian stimulation.',
  '24-36 hours',
  'Store in refrigerator (2-8°C)',
  '["Supports ovulation"]'::jsonb,
  '["Ovarian hyperstimulation"]'::jsonb,
  '["Pregnancy, ovarian cysts"]'::jsonb,
  '[{"vialSize": "STANDARD", "reconstitution": "Mix per vial instructions", "frequency": "Dose 75-225IU daily subcutaneously", "subcutaneous": "75-225IU daily subcutaneously"}]'::jsonb,
  '["HCG: Ovulation trigger"]'::jsonb,
  '❤️'
),
(
  'EPO',
  '3000iu',
  'Various',
  'Immune Support',
  'Erythropoietin for red blood cell production.',
  'Stimulates erythropoiesis.',
  '24-48 hours',
  'Store in refrigerator (2-8°C)',
  '["Increases oxygen capacity"]'::jsonb,
  '["Hypertension, thrombosis"]'::jsonb,
  '["Cancer, CV disease"]'::jsonb,
  '[{"vialSize": "STANDARD", "reconstitution": "Dose 50-100IU/kg 3x/week subcutaneous", "frequency": "Dose 50-100IU/kg 3x/week subcutaneous", "subcutaneous": "Dose 50-100IU/kg 3x/week subcutaneous"}]'::jsonb,
  '["Avoid with other performance enhancers"]'::jsonb,
  '🔬'
),
(
  'Insulin',
  '100iu/3ml',
  'Various',
  'Accessories & Supplies',
  'A peptide hormone for glucose uptake.',
  'Binds insulin receptors to lower blood sugar.',
  '2-4 hours',
  'Store in refrigerator (2-8°C)',
  '["Glycemic management"]'::jsonb,
  '["Hypoglycemia"]'::jsonb,
  '["Hypoglycemia risk"]'::jsonb,
  '[{"vialSize": "STANDARD", "reconstitution": "Dose per research protocol, subcutaneous", "frequency": "Dose per research protocol, subcutaneous", "subcutaneous": "Dose per research protocol, subcutaneous"}]'::jsonb,
  '["Use with caution in metabolic studies"]'::jsonb,
  '🔬'
),
(
  'Botulinum toxin',
  '100iu, 1000iu',
  'Various',
  'Accessories & Supplies',
  'A neurotoxin peptide for muscle relaxation and cosmetic use.',
  'Blocks acetylcholine release to relax muscles.',
  '3-6 months',
  'Store in refrigerator (2-8°C)',
  '["Reduces wrinkles, muscle spasms"]'::jsonb,
  '["Bruising, temporary weakness"]'::jsonb,
  '["Neuromuscular disorders, hypersensitivity"]'::jsonb,
  '[{"vialSize": "100U", "reconstitution": "Reconstitute per vial (typically 2-4mL saline)", "frequency": "Dose 2-5U per site, every 3-6 months", "subcutaneous": "2-5U per site, every 3-6 months"}]'::jsonb,
  '["Snap-8: Cosmetic synergy"]'::jsonb,
  '✨'
);

-- Bacteriostatic Water
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, storage, icon) VALUES
(
  'Bacteriostatic Water (Benzyl Alcohol 0.9%)',
  '3ml, 10ml',
  'Various',
  'Accessories & Supplies',
  'Sterile water with benzyl alcohol for peptide reconstitution.',
  'Provides sterile solvent for peptide preparation.',
  'Store in refrigerator (2-8°C)',
  '🔬'
),
(
  'Phosphate Buffered Saline',
  '3ml',
  'Various',
  'Accessories & Supplies',
  'Buffered saline solution for peptide reconstitution.',
  'pH-balanced solvent for sensitive peptides.',
  'Store in refrigerator (2-8°C)',
  '🔬'
),
(
  'Acetic Acid 0.6%',
  '3ml, 10ml',
  'Various',
  'Accessories & Supplies',
  'Acidic solution for peptide reconstitution.',
  'Maintains peptide stability in acidic conditions.',
  'Store in refrigerator (2-8°C)',
  '🔬'
);

-- Final update to set is_active flag for all peptides
UPDATE peptides SET is_active = true WHERE is_active IS NULL;

