-- Comprehensive Peptide Data - Separated by Strength with Pricing
-- Each strength variant is a separate product entry with complete pricing information

-- Clear existing peptides (optional - comment out if you want to preserve existing data)
-- TRUNCATE TABLE peptides CASCADE;

-- ============================================================================
-- WEIGHT LOSS & METABOLIC PEPTIDES
-- ============================================================================

-- Semaglutide variants
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon, is_active, vials_per_box, price_per_vial, price_per_box) VALUES
('Semaglutide', '2mg', 'Various', 'Weight Loss & Metabolic', 'A GLP-1 receptor agonist originally developed for type 2 diabetes management but widely researched for obesity due to its potent appetite suppression and metabolic effects.', 'GLP-1 receptor agonist that suppresses appetite via hypothalamic signaling, slows gastric emptying, and promotes insulin release while inhibiting glucagon.', '7 days', 'Store in refrigerator (2-8°C)', '["Average weight loss of 15-20% over 68 weeks in trials", "Improves glycemic control and cardiovascular risk factors", "Enhances satiety and reduces cravings", "Supports fat oxidation and insulin sensitivity"]'::jsonb, '["Injection site reactions (redness, swelling)", "Nausea, vomiting, diarrhea, constipation", "Fatigue, abdominal pain, decreased appetite", "Rare: Pancreatitis, gallbladder disease, thyroid tumors"]'::jsonb, '["Do not use if pregnant, breastfeeding, or history of medullary thyroid carcinoma/MEN 2", "Avoid in type 1 diabetes, severe GI disease, or hypersensitivity"]'::jsonb, '[{"vialSize": "2MG", "reconstitution": "Mix with 0.4mL (40 units) BAC water", "frequency": "Dose once weekly subcutaneously", "subcutaneous": "8 units = 0.25mg; 16 units = 0.5mg; 24 units = 0.75mg; 32 units = 1mg"}]'::jsonb, '["Tirzepatide: Enhanced weight loss", "Cagrilintide: Amplified satiety", "AOD-9604: Boosts lipolysis", "BPC-157: Mitigates GI side effects"]'::jsonb, '💊', true, 10, 465.75, 4657.50),
('Semaglutide', '5mg', 'Various', 'Weight Loss & Metabolic', 'A GLP-1 receptor agonist originally developed for type 2 diabetes management but widely researched for obesity due to its potent appetite suppression and metabolic effects.', 'GLP-1 receptor agonist that suppresses appetite via hypothalamic signaling, slows gastric emptying, and promotes insulin release while inhibiting glucagon.', '7 days', 'Store in refrigerator (2-8°C)', '["Average weight loss of 15-20% over 68 weeks in trials", "Improves glycemic control and cardiovascular risk factors", "Enhances satiety and reduces cravings", "Supports fat oxidation and insulin sensitivity"]'::jsonb, '["Injection site reactions (redness, swelling)", "Nausea, vomiting, diarrhea, constipation", "Fatigue, abdominal pain, decreased appetite", "Rare: Pancreatitis, gallbladder disease, thyroid tumors"]'::jsonb, '["Do not use if pregnant, breastfeeding, or history of medullary thyroid carcinoma/MEN 2", "Avoid in type 1 diabetes, severe GI disease, or hypersensitivity"]'::jsonb, '[{"vialSize": "5MG", "reconstitution": "Mix with 1mL (100 units) BAC water", "frequency": "Dose once weekly subcutaneously", "subcutaneous": "5 units = 0.25mg; 10 units = 0.5mg; 20 units = 1mg; 30 units = 1.5mg; 40 units = 2mg"}]'::jsonb, '["Tirzepatide: Enhanced weight loss", "Cagrilintide: Amplified satiety", "AOD-9604: Boosts lipolysis", "BPC-157: Mitigates GI side effects"]'::jsonb, '💊', true, 10, 477.25, 4772.50),
('Semaglutide', '10mg', 'Various', 'Weight Loss & Metabolic', 'A GLP-1 receptor agonist originally developed for type 2 diabetes management but widely researched for obesity due to its potent appetite suppression and metabolic effects.', 'GLP-1 receptor agonist that suppresses appetite via hypothalamic signaling, slows gastric emptying, and promotes insulin release while inhibiting glucagon.', '7 days', 'Store in refrigerator (2-8°C)', '["Average weight loss of 15-20% over 68 weeks in trials", "Improves glycemic control and cardiovascular risk factors", "Enhances satiety and reduces cravings", "Supports fat oxidation and insulin sensitivity"]'::jsonb, '["Injection site reactions (redness, swelling)", "Nausea, vomiting, diarrhea, constipation", "Fatigue, abdominal pain, decreased appetite", "Rare: Pancreatitis, gallbladder disease, thyroid tumors"]'::jsonb, '["Do not use if pregnant, breastfeeding, or history of medullary thyroid carcinoma/MEN 2", "Avoid in type 1 diabetes, severe GI disease, or hypersensitivity"]'::jsonb, '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL (200 units) BAC water", "frequency": "Dose once weekly subcutaneously", "subcutaneous": "10 units = 0.5mg; 20 units = 1mg; 30 units = 1.5mg; 40 units = 2mg; 50 units = 2.5mg"}]'::jsonb, '["Tirzepatide: Enhanced weight loss", "Cagrilintide: Amplified satiety", "AOD-9604: Boosts lipolysis", "BPC-157: Mitigates GI side effects"]'::jsonb, '💊', true, 10, 523.25, 5232.50),
('Semaglutide', '15mg', 'Various', 'Weight Loss & Metabolic', 'A GLP-1 receptor agonist originally developed for type 2 diabetes management but widely researched for obesity due to its potent appetite suppression and metabolic effects.', 'GLP-1 receptor agonist that suppresses appetite via hypothalamic signaling, slows gastric emptying, and promotes insulin release while inhibiting glucagon.', '7 days', 'Store in refrigerator (2-8°C)', '["Average weight loss of 15-20% over 68 weeks in trials", "Improves glycemic control and cardiovascular risk factors", "Enhances satiety and reduces cravings", "Supports fat oxidation and insulin sensitivity"]'::jsonb, '["Injection site reactions (redness, swelling)", "Nausea, vomiting, diarrhea, constipation", "Fatigue, abdominal pain, decreased appetite", "Rare: Pancreatitis, gallbladder disease, thyroid tumors"]'::jsonb, '["Do not use if pregnant, breastfeeding, or history of medullary thyroid carcinoma/MEN 2", "Avoid in type 1 diabetes, severe GI disease, or hypersensitivity"]'::jsonb, '[{"vialSize": "15MG", "reconstitution": "Mix with 3mL (300 units) BAC water", "frequency": "Dose once weekly subcutaneously", "subcutaneous": "10 units = 0.5mg; 20 units = 1mg; 40 units = 2mg; 60 units = 3mg"}]'::jsonb, '["Tirzepatide: Enhanced weight loss", "Cagrilintide: Amplified satiety", "AOD-9604: Boosts lipolysis", "BPC-157: Mitigates GI side effects"]'::jsonb, '💊', true, 10, 603.75, 6037.50),
('Semaglutide', '20mg', 'Various', 'Weight Loss & Metabolic', 'A GLP-1 receptor agonist originally developed for type 2 diabetes management but widely researched for obesity due to its potent appetite suppression and metabolic effects.', 'GLP-1 receptor agonist that suppresses appetite via hypothalamic signaling, slows gastric emptying, and promotes insulin release while inhibiting glucagon.', '7 days', 'Store in refrigerator (2-8°C)', '["Average weight loss of 15-20% over 68 weeks in trials", "Improves glycemic control and cardiovascular risk factors", "Enhances satiety and reduces cravings", "Supports fat oxidation and insulin sensitivity"]'::jsonb, '["Injection site reactions (redness, swelling)", "Nausea, vomiting, diarrhea, constipation", "Fatigue, abdominal pain, decreased appetite", "Rare: Pancreatitis, gallbladder disease, thyroid tumors"]'::jsonb, '["Do not use if pregnant, breastfeeding, or history of medullary thyroid carcinoma/MEN 2", "Avoid in type 1 diabetes, severe GI disease, or hypersensitivity"]'::jsonb, '[{"vialSize": "20MG", "reconstitution": "Mix with 4mL (400 units) BAC water", "frequency": "Dose once weekly subcutaneously", "subcutaneous": "10 units = 0.5mg; 20 units = 1mg; 40 units = 2mg; 80 units = 4mg"}]'::jsonb, '["Tirzepatide: Enhanced weight loss", "Cagrilintide: Amplified satiety", "AOD-9604: Boosts lipolysis", "BPC-157: Mitigates GI side effects"]'::jsonb, '💊', true, 10, 707.25, 7072.50),
('Semaglutide', '30mg', 'Various', 'Weight Loss & Metabolic', 'A GLP-1 receptor agonist originally developed for type 2 diabetes management but widely researched for obesity due to its potent appetite suppression and metabolic effects.', 'GLP-1 receptor agonist that suppresses appetite via hypothalamic signaling, slows gastric emptying, and promotes insulin release while inhibiting glucagon.', '7 days', 'Store in refrigerator (2-8°C)', '["Average weight loss of 15-20% over 68 weeks in trials", "Improves glycemic control and cardiovascular risk factors", "Enhances satiety and reduces cravings", "Supports fat oxidation and insulin sensitivity"]'::jsonb, '["Injection site reactions (redness, swelling)", "Nausea, vomiting, diarrhea, constipation", "Fatigue, abdominal pain, decreased appetite", "Rare: Pancreatitis, gallbladder disease, thyroid tumors"]'::jsonb, '["Do not use if pregnant, breastfeeding, or history of medullary thyroid carcinoma/MEN 2", "Avoid in type 1 diabetes, severe GI disease, or hypersensitivity"]'::jsonb, '[{"vialSize": "30MG", "reconstitution": "Mix with 6mL (600 units) BAC water", "frequency": "Dose once weekly subcutaneously", "subcutaneous": "10 units = 0.5mg; 20 units = 1mg; 40 units = 2mg; 60 units = 3mg"}]'::jsonb, '["Tirzepatide: Enhanced weight loss", "Cagrilintide: Amplified satiety", "AOD-9604: Boosts lipolysis", "BPC-157: Mitigates GI side effects"]'::jsonb, '💊', true, 10, 844.05, 8440.45);

-- Tirzepatide variants
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon, is_active, vials_per_box, price_per_vial, price_per_box) VALUES
('Tirzepatide', '5mg', 'Various', 'Weight Loss & Metabolic', 'A dual agonist of the GLP-1 and GIP receptors originally developed to treat Type-2 diabetes but has since become a leading anti-obesity medication.', 'Dual agonist of GLP-1 and GIP receptors. GLP-1 suppresses appetite. GIP promotes insulin secretion and supports energy balance.', '5 days', 'Store in refrigerator (2-8°C)', '["Average weight loss of 24.7% after 72 weeks", "Reduces appetite and cravings", "Enhances satiety and energy balance", "Improves insulin sensitivity"]'::jsonb, '["Injection site reactions", "Nausea, vomiting, diarrhea", "Decreased appetite, fatigue", "Rare: Thyroid C-Cell Tumors, Pancreatitis"]'::jsonb, '["Do not use if pregnant or breastfeeding", "Do not use with history of Medullary Thyroid Carcinoma or MEN 2", "Avoid in Type-1 diabetes or severe GI disease"]'::jsonb, '[{"vialSize": "5MG", "reconstitution": "Mix with 0.5mL (50 units) BAC water", "frequency": "Dose weekly, minimum 4 weeks per level", "subcutaneous": "12 units = 1.2mg; 25 units = 2.5mg; 38 units = 3.8mg; 50 units = 5mg"}]'::jsonb, '["AOD-9604: Enhanced fat breakdown", "Tesamorelin: Synergistic fat reduction", "NAD+: Energy support", "BPC-157: Gut repair"]'::jsonb, '💊', true, 10, 378.37, 3783.65),
('Tirzepatide', '10mg', 'Various', 'Weight Loss & Metabolic', 'A dual agonist of the GLP-1 and GIP receptors originally developed to treat Type-2 diabetes but has since become a leading anti-obesity medication.', 'Dual agonist of GLP-1 and GIP receptors. GLP-1 suppresses appetite. GIP promotes insulin secretion and supports energy balance.', '5 days', 'Store in refrigerator (2-8°C)', '["Average weight loss of 24.7% after 72 weeks", "Reduces appetite and cravings", "Enhances satiety and energy balance", "Improves insulin sensitivity"]'::jsonb, '["Injection site reactions", "Nausea, vomiting, diarrhea", "Decreased appetite, fatigue", "Rare: Thyroid C-Cell Tumors, Pancreatitis"]'::jsonb, '["Do not use if pregnant or breastfeeding", "Do not use with history of Medullary Thyroid Carcinoma or MEN 2", "Avoid in Type-1 diabetes or severe GI disease"]'::jsonb, '[{"vialSize": "10MG", "reconstitution": "Mix with 0.5mL (50 units) BAC water", "frequency": "Dose weekly, minimum 4 weeks per level", "subcutaneous": "12 units = 2.5mg; 25 units = 5mg; 38 units = 7.5mg; 50 units = 10mg"}]'::jsonb, '["AOD-9604: Enhanced fat breakdown", "Tesamorelin: Synergistic fat reduction", "NAD+: Energy support", "BPC-157: Gut repair"]'::jsonb, '💊', true, 10, 465.68, 4656.80),
('Tirzepatide', '15mg', 'Various', 'Weight Loss & Metabolic', 'A dual agonist of the GLP-1 and GIP receptors originally developed to treat Type-2 diabetes but has since become a leading anti-obesity medication.', 'Dual agonist of GLP-1 and GIP receptors. GLP-1 suppresses appetite. GIP promotes insulin secretion and supports energy balance.', '5 days', 'Store in refrigerator (2-8°C)', '["Average weight loss of 24.7% after 72 weeks", "Reduces appetite and cravings", "Enhances satiety and energy balance", "Improves insulin sensitivity"]'::jsonb, '["Injection site reactions", "Nausea, vomiting, diarrhea", "Decreased appetite, fatigue", "Rare: Thyroid C-Cell Tumors, Pancreatitis"]'::jsonb, '["Do not use if pregnant or breastfeeding", "Do not use with history of Medullary Thyroid Carcinoma or MEN 2", "Avoid in Type-1 diabetes or severe GI disease"]'::jsonb, '[{"vialSize": "15MG", "reconstitution": "Mix with 0.75mL (75 units) BAC water", "frequency": "Dose weekly, minimum 4 weeks per level", "subcutaneous": "12 units = 2.5mg; 25 units = 5mg; 50 units = 10mg; 75 units = 15mg"}]'::jsonb, '["AOD-9604: Enhanced fat breakdown", "Tesamorelin: Synergistic fat reduction", "NAD+: Energy support", "BPC-157: Gut repair"]'::jsonb, '💊', true, 10, 622.85, 6228.47),
('Tirzepatide', '20mg', 'Various', 'Weight Loss & Metabolic', 'A dual agonist of the GLP-1 and GIP receptors originally developed to treat Type-2 diabetes but has since become a leading anti-obesity medication.', 'Dual agonist of GLP-1 and GIP receptors. GLP-1 suppresses appetite. GIP promotes insulin secretion and supports energy balance.', '5 days', 'Store in refrigerator (2-8°C)', '["Average weight loss of 24.7% after 72 weeks", "Reduces appetite and cravings", "Enhances satiety and energy balance", "Improves insulin sensitivity"]'::jsonb, '["Injection site reactions", "Nausea, vomiting, diarrhea", "Decreased appetite, fatigue", "Rare: Thyroid C-Cell Tumors, Pancreatitis"]'::jsonb, '["Do not use if pregnant or breastfeeding", "Do not use with history of Medullary Thyroid Carcinoma or MEN 2", "Avoid in Type-1 diabetes or severe GI disease"]'::jsonb, '[{"vialSize": "20MG", "reconstitution": "Mix with 1mL (100 units) BAC water", "frequency": "Dose weekly, minimum 4 weeks per level", "subcutaneous": "12 units = 2.5mg; 25 units = 5mg; 50 units = 10mg; 75 units = 15mg"}]'::jsonb, '["AOD-9604: Enhanced fat breakdown", "Tesamorelin: Synergistic fat reduction", "NAD+: Energy support", "BPC-157: Gut repair"]'::jsonb, '💊', true, 10, 698.52, 6985.20),
('Tirzepatide', '30mg', 'Various', 'Weight Loss & Metabolic', 'A dual agonist of the GLP-1 and GIP receptors originally developed to treat Type-2 diabetes but has since become a leading anti-obesity medication.', 'Dual agonist of GLP-1 and GIP receptors. GLP-1 suppresses appetite. GIP promotes insulin secretion and supports energy balance.', '5 days', 'Store in refrigerator (2-8°C)', '["Average weight loss of 24.7% after 72 weeks", "Reduces appetite and cravings", "Enhances satiety and energy balance", "Improves insulin sensitivity"]'::jsonb, '["Injection site reactions", "Nausea, vomiting, diarrhea", "Decreased appetite, fatigue", "Rare: Thyroid C-Cell Tumors, Pancreatitis"]'::jsonb, '["Do not use if pregnant or breastfeeding", "Do not use with history of Medullary Thyroid Carcinoma or MEN 2", "Avoid in Type-1 diabetes or severe GI disease"]'::jsonb, '[{"vialSize": "30MG", "reconstitution": "Mix with 1.5mL (150 units) BAC water", "frequency": "Dose weekly, minimum 4 weeks per level", "subcutaneous": "12 units = 2.5mg; 25 units = 5mg; 50 units = 10mg; 75 units = 15mg"}]'::jsonb, '["AOD-9604: Enhanced fat breakdown", "Tesamorelin: Synergistic fat reduction", "NAD+: Energy support", "BPC-157: Gut repair"]'::jsonb, '💊', true, 10, 832.40, 8324.03),
('Tirzepatide', '40mg', 'Various', 'Weight Loss & Metabolic', 'A dual agonist of the GLP-1 and GIP receptors originally developed to treat Type-2 diabetes but has since become a leading anti-obesity medication.', 'Dual agonist of GLP-1 and GIP receptors. GLP-1 suppresses appetite. GIP promotes insulin secretion and supports energy balance.', '5 days', 'Store in refrigerator (2-8°C)', '["Average weight loss of 24.7% after 72 weeks", "Reduces appetite and cravings", "Enhances satiety and energy balance", "Improves insulin sensitivity"]'::jsonb, '["Injection site reactions", "Nausea, vomiting, diarrhea", "Decreased appetite, fatigue", "Rare: Thyroid C-Cell Tumors, Pancreatitis"]'::jsonb, '["Do not use if pregnant or breastfeeding", "Do not use with history of Medullary Thyroid Carcinoma or MEN 2", "Avoid in Type-1 diabetes or severe GI disease"]'::jsonb, '[{"vialSize": "40MG", "reconstitution": "Mix with 2mL (200 units) BAC water", "frequency": "Dose weekly, minimum 4 weeks per level", "subcutaneous": "12 units = 2.5mg; 25 units = 5mg; 50 units = 10mg"}]'::jsonb, '["AOD-9604: Enhanced fat breakdown", "Tesamorelin: Synergistic fat reduction", "NAD+: Energy support", "BPC-157: Gut repair"]'::jsonb, '💊', true, 10, 1001.21, 10012.12),
('Tirzepatide', '50mg', 'Various', 'Weight Loss & Metabolic', 'A dual agonist of the GLP-1 and GIP receptors originally developed to treat Type-2 diabetes but has since become a leading anti-obesity medication.', 'Dual agonist of GLP-1 and GIP receptors. GLP-1 suppresses appetite. GIP promotes insulin secretion and supports energy balance.', '5 days', 'Store in refrigerator (2-8°C)', '["Average weight loss of 24.7% after 72 weeks", "Reduces appetite and cravings", "Enhances satiety and energy balance", "Improves insulin sensitivity"]'::jsonb, '["Injection site reactions", "Nausea, vomiting, diarrhea", "Decreased appetite, fatigue", "Rare: Thyroid C-Cell Tumors, Pancreatitis"]'::jsonb, '["Do not use if pregnant or breastfeeding", "Do not use with history of Medullary Thyroid Carcinoma or MEN 2", "Avoid in Type-1 diabetes or severe GI disease"]'::jsonb, '[{"vialSize": "50MG", "reconstitution": "Mix with 2.5mL (250 units) BAC water", "frequency": "Dose weekly, minimum 4 weeks per level", "subcutaneous": "12 units = 2.5mg; 25 units = 5mg; 50 units = 10mg"}]'::jsonb, '["AOD-9604: Enhanced fat breakdown", "Tesamorelin: Synergistic fat reduction", "NAD+: Energy support", "BPC-157: Gut repair"]'::jsonb, '💊', true, 10, 1181.66, 11816.63),
('Tirzepatide', '60mg', 'Various', 'Weight Loss & Metabolic', 'A dual agonist of the GLP-1 and GIP receptors originally developed to treat Type-2 diabetes but has since become a leading anti-obesity medication.', 'Dual agonist of GLP-1 and GIP receptors. GLP-1 suppresses appetite. GIP promotes insulin secretion and supports energy balance.', '5 days', 'Store in refrigerator (2-8°C)', '["Average weight loss of 24.7% after 72 weeks", "Reduces appetite and cravings", "Enhances satiety and energy balance", "Improves insulin sensitivity"]'::jsonb, '["Injection site reactions", "Nausea, vomiting, diarrhea", "Decreased appetite, fatigue", "Rare: Thyroid C-Cell Tumors, Pancreatitis"]'::jsonb, '["Do not use if pregnant or breastfeeding", "Do not use with history of Medullary Thyroid Carcinoma or MEN 2", "Avoid in Type-1 diabetes or severe GI disease"]'::jsonb, '[{"vialSize": "60MG", "reconstitution": "Mix with 3mL (300 units) BAC water", "frequency": "Dose weekly, minimum 4 weeks per level", "subcutaneous": "12 units = 2.5mg; 25 units = 5mg; 50 units = 10mg"}]'::jsonb, '["AOD-9604: Enhanced fat breakdown", "Tesamorelin: Synergistic fat reduction", "NAD+: Energy support", "BPC-157: Gut repair"]'::jsonb, '💊', true, 10, 1414.50, 14145.03);

-- Retatrutide variants
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon, is_active, vials_per_box, price_per_vial, price_per_box) VALUES
('Retatrutide', '5mg', 'Various', 'Weight Loss & Metabolic', 'A powerful triple agonist peptide that targets GLP-1, GIP, and glucagon receptors—making it the most comprehensive metabolic peptide in its class.', 'Triple agonist peptide targeting GLP-1, GIP, and glucagon receptors for appetite suppression, insulin secretion, and increased energy expenditure.', '6 days', 'Store in refrigerator (2-8°C)', '["Superior weight loss up to 24% in 48 weeks", "Improves glycemic control and liver fat reduction", "Enhances metabolic rate", "Rapid and sustained fat loss"]'::jsonb, '["Gastrointestinal issues (nausea, diarrhea)", "Injection site reactions", "Fatigue, mild heart rate increase", "Rare: Pancreatitis, thyroid concerns"]'::jsonb, '["Avoid in pregnancy, breastfeeding, or thyroid cancer history", "Not for type 1 diabetes or severe GI disorders", "Hypersensitivity to components"]'::jsonb, '[{"vialSize": "5MG", "reconstitution": "Mix with 1mL (100 units) BAC water", "frequency": "Dose weekly subcutaneously", "subcutaneous": "20 units = 1mg; 40 units = 2mg; 60 units = 3mg; 80 units = 4mg; 100 units = 5mg"}]'::jsonb, '["Semaglutide: For dual GLP-1 enhancement", "Glutathione: For detox support", "LIPO-C: Energy and fat breakdown", "BPC-157: Gut protection"]'::jsonb, '💊', true, 10, 553.00, 5529.95),
('Retatrutide', '10mg', 'Various', 'Weight Loss & Metabolic', 'A powerful triple agonist peptide that targets GLP-1, GIP, and glucagon receptors—making it the most comprehensive metabolic peptide in its class.', 'Triple agonist peptide targeting GLP-1, GIP, and glucagon receptors for appetite suppression, insulin secretion, and increased energy expenditure.', '6 days', 'Store in refrigerator (2-8°C)', '["Superior weight loss up to 24% in 48 weeks", "Improves glycemic control and liver fat reduction", "Enhances metabolic rate", "Rapid and sustained fat loss"]'::jsonb, '["Gastrointestinal issues (nausea, diarrhea)", "Injection site reactions", "Fatigue, mild heart rate increase", "Rare: Pancreatitis, thyroid concerns"]'::jsonb, '["Avoid in pregnancy, breastfeeding, or thyroid cancer history", "Not for type 1 diabetes or severe GI disorders", "Hypersensitivity to components"]'::jsonb, '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL (200 units) BAC water", "frequency": "Dose weekly subcutaneously", "subcutaneous": "20 units = 1mg; 40 units = 2mg; 80 units = 4mg; 120 units = 6mg; 200 units = 10mg"}]'::jsonb, '["Semaglutide: For dual GLP-1 enhancement", "Glutathione: For detox support", "LIPO-C: Energy and fat breakdown", "BPC-157: Gut protection"]'::jsonb, '💊', true, 10, 750.91, 7509.09),
('Retatrutide', '15mg', 'Various', 'Weight Loss & Metabolic', 'A powerful triple agonist peptide that targets GLP-1, GIP, and glucagon receptors—making it the most comprehensive metabolic peptide in its class.', 'Triple agonist peptide targeting GLP-1, GIP, and glucagon receptors for appetite suppression, insulin secretion, and increased energy expenditure.', '6 days', 'Store in refrigerator (2-8°C)', '["Superior weight loss up to 24% in 48 weeks", "Improves glycemic control and liver fat reduction", "Enhances metabolic rate", "Rapid and sustained fat loss"]'::jsonb, '["Gastrointestinal issues (nausea, diarrhea)", "Injection site reactions", "Fatigue, mild heart rate increase", "Rare: Pancreatitis, thyroid concerns"]'::jsonb, '["Avoid in pregnancy, breastfeeding, or thyroid cancer history", "Not for type 1 diabetes or severe GI disorders", "Hypersensitivity to components"]'::jsonb, '[{"vialSize": "15MG", "reconstitution": "Mix with 3mL (300 units) BAC water", "frequency": "Dose weekly subcutaneously", "subcutaneous": "20 units = 1mg; 40 units = 2mg; 80 units = 4mg; 120 units = 6mg; 200 units = 10mg"}]'::jsonb, '["Semaglutide: For dual GLP-1 enhancement", "Glutathione: For detox support", "LIPO-C: Energy and fat breakdown", "BPC-157: Gut protection"]'::jsonb, '💊', true, 10, 925.54, 9255.39),
('Retatrutide', '20mg', 'Various', 'Weight Loss & Metabolic', 'A powerful triple agonist peptide that targets GLP-1, GIP, and glucagon receptors—making it the most comprehensive metabolic peptide in its class.', 'Triple agonist peptide targeting GLP-1, GIP, and glucagon receptors for appetite suppression, insulin secretion, and increased energy expenditure.', '6 days', 'Store in refrigerator (2-8°C)', '["Superior weight loss up to 24% in 48 weeks", "Improves glycemic control and liver fat reduction", "Enhances metabolic rate", "Rapid and sustained fat loss"]'::jsonb, '["Gastrointestinal issues (nausea, diarrhea)", "Injection site reactions", "Fatigue, mild heart rate increase", "Rare: Pancreatitis, thyroid concerns"]'::jsonb, '["Avoid in pregnancy, breastfeeding, or thyroid cancer history", "Not for type 1 diabetes or severe GI disorders", "Hypersensitivity to components"]'::jsonb, '[{"vialSize": "20MG", "reconstitution": "Mix with 4mL (400 units) BAC water", "frequency": "Dose weekly subcutaneously", "subcutaneous": "20 units = 1mg; 40 units = 2mg; 80 units = 4mg; 120 units = 6mg; 200 units = 10mg"}]'::jsonb, '["Semaglutide: For dual GLP-1 enhancement", "Glutathione: For detox support", "LIPO-C: Energy and fat breakdown", "BPC-157: Gut protection"]'::jsonb, '💊', true, 10, 1076.89, 10768.85),
('Retatrutide', '30mg', 'Various', 'Weight Loss & Metabolic', 'A powerful triple agonist peptide that targets GLP-1, GIP, and glucagon receptors—making it the most comprehensive metabolic peptide in its class.', 'Triple agonist peptide targeting GLP-1, GIP, and glucagon receptors for appetite suppression, insulin secretion, and increased energy expenditure.', '6 days', 'Store in refrigerator (2-8°C)', '["Superior weight loss up to 24% in 48 weeks", "Improves glycemic control and liver fat reduction", "Enhances metabolic rate", "Rapid and sustained fat loss"]'::jsonb, '["Gastrointestinal issues (nausea, diarrhea)", "Injection site reactions", "Fatigue, mild heart rate increase", "Rare: Pancreatitis, thyroid concerns"]'::jsonb, '["Avoid in pregnancy, breastfeeding, or thyroid cancer history", "Not for type 1 diabetes or severe GI disorders", "Hypersensitivity to components"]'::jsonb, '[{"vialSize": "30MG", "reconstitution": "Mix with 6mL (600 units) BAC water", "frequency": "Dose weekly subcutaneously", "subcutaneous": "20 units = 1mg; 40 units = 2mg; 80 units = 4mg; 120 units = 6mg"}]'::jsonb, '["Semaglutide: For dual GLP-1 enhancement", "Glutathione: For detox support", "LIPO-C: Energy and fat breakdown", "BPC-157: Gut protection"]'::jsonb, '💊', true, 10, 1338.83, 13388.30);

-- ============================================================================
-- HEALING & RECOVERY PEPTIDES
-- ============================================================================

-- BPC-157 variants
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon, is_active, vials_per_box, price_per_vial, price_per_box) VALUES
('BPC-157', '5mg', 'Various', 'Healing & Recovery', 'A synthetic peptide derived from a protein in human gastric juice, researched for its regenerative effects on tissues throughout the body.', 'Synthetic peptide that upregulates growth factors, enhances angiogenesis, and protects GI mucosa.', '4-6 hours', 'Store in refrigerator (2-8°C)', '["Accelerates tendon, ligament, muscle, and GI healing", "Reduces inflammation", "Systemic repair support"]'::jsonb, '["Minimal; possible injection site reactions"]'::jsonb, '["Hypersensitivity"]'::jsonb, '[{"vialSize": "5MG", "reconstitution": "Mix with 2mL (200 units) BAC water", "frequency": "Dose daily subcutaneously", "subcutaneous": "250-500mcg (25-50 units) daily"}]'::jsonb, '["TB-500: Synergistic repair", "GHK-Cu: Skin and connective tissue"]'::jsonb, '🩹', true, 10, 345.00, 3450.00),
('BPC-157', '10mg', 'Various', 'Healing & Recovery', 'A synthetic peptide derived from a protein in human gastric juice, researched for its regenerative effects on tissues throughout the body.', 'Synthetic peptide that upregulates growth factors, enhances angiogenesis, and protects GI mucosa.', '4-6 hours', 'Store in refrigerator (2-8°C)', '["Accelerates tendon, ligament, muscle, and GI healing", "Reduces inflammation", "Systemic repair support"]'::jsonb, '["Minimal; possible injection site reactions"]'::jsonb, '["Hypersensitivity"]'::jsonb, '[{"vialSize": "10MG", "reconstitution": "Mix with 4mL (400 units) BAC water", "frequency": "Dose daily subcutaneously", "subcutaneous": "250-500mcg (10-20 units) daily"}]'::jsonb, '["TB-500: Synergistic repair", "GHK-Cu: Skin and connective tissue"]'::jsonb, '🩹', true, 10, 500.25, 5002.50);

-- TB-500 variants
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon, is_active, vials_per_box, price_per_vial, price_per_box) VALUES
('TB-500', '5mg', 'Various', 'Healing & Recovery', 'A synthetic version of Thymosin Beta-4, a peptide involved in actin regulation for tissue repair and healing.', 'Promotes actin polymerization for cell migration, angiogenesis, and anti-inflammatory effects.', '2-4 hours', 'Store in refrigerator (2-8°C)', '["Accelerates muscle, tendon, and wound healing", "Improves flexibility and reduces scarring", "Enhances recovery"]'::jsonb, '["Headaches, nausea, injection site reactions"]'::jsonb, '["Cancer history (angiogenesis risk)"]'::jsonb, '[{"vialSize": "5MG", "reconstitution": "Mix with 2.5mL (250 units) BAC water", "frequency": "Loading: 4-8mg/week divided 2-3x", "subcutaneous": "Loading: 4-8mg/week (8-16 units 2x/week)"}]'::jsonb, '["BPC-157: Comprehensive healing", "GHK-Cu: Collagen support"]'::jsonb, '🩹', true, 10, 541.35, 5413.53),
('TB-500', '10mg', 'Various', 'Healing & Recovery', 'A synthetic version of Thymosin Beta-4, a peptide involved in actin regulation for tissue repair and healing.', 'Promotes actin polymerization for cell migration, angiogenesis, and anti-inflammatory effects.', '2-4 hours', 'Store in refrigerator (2-8°C)', '["Accelerates muscle, tendon, and wound healing", "Improves flexibility and reduces scarring", "Enhances recovery"]'::jsonb, '["Headaches, nausea, injection site reactions"]'::jsonb, '["Cancer history (angiogenesis risk)"]'::jsonb, '[{"vialSize": "10MG", "reconstitution": "Mix with 5mL (500 units) BAC water", "frequency": "Loading: 4-8mg/week divided 2-3x", "subcutaneous": "Loading: 4-8mg/week (4-8 units 2x/week)"}]'::jsonb, '["BPC-157: Comprehensive healing", "GHK-Cu: Collagen support"]'::jsonb, '🩹', true, 10, 919.72, 9197.18);

-- Ipamorelin variants
INSERT INTO peptides (name, strength, vendor, category, description, mechanism, half_life, storage, benefits, side_effects, contraindications, dosing, stacking, icon, is_active, vials_per_box, price_per_vial, price_per_box) VALUES
('Ipamorelin', '5mg', 'Various', 'Growth Hormone', 'A selective growth hormone secretagogue and ghrelin receptor agonist, promoting GH release without cortisol/prolactin spikes.', 'Selective growth hormone secretagogue promoting GH release without cortisol/prolactin spikes.', '2 hours', 'Store in refrigerator (2-8°C)', '["Increases GH for muscle growth and recovery", "Improves sleep and metabolism", "Enhances energy"]'::jsonb, '["Mild hunger, flushing", "Injection site reactions"]'::jsonb, '["Hypersensitivity, active malignancy"]'::jsonb, '[{"vialSize": "5MG", "reconstitution": "Mix with 1mL (100 units) BAC water", "frequency": "Dose nightly subcutaneously, 5 days/week", "subcutaneous": "100-300mcg (2-6 units) nightly"}]'::jsonb, '["CJC-1295: Synergistic GH release", "Tesamorelin: Fat reduction"]'::jsonb, '🩹', true, 10, 345.00, 3450.00),
('Ipamorelin', '10mg', 'Various', 'Growth Hormone', 'A selective growth hormone secretagogue and ghrelin receptor agonist, promoting GH release without cortisol/prolactin spikes.', 'Selective growth hormone secretagogue promoting GH release without cortisol/prolactin spikes.', '2 hours', 'Store in refrigerator (2-8°C)', '["Increases GH for muscle growth and recovery", "Improves sleep and metabolism", "Enhances energy"]'::jsonb, '["Mild hunger, flushing", "Injection site reactions"]'::jsonb, '["Hypersensitivity, active malignancy"]'::jsonb, '[{"vialSize": "10MG", "reconstitution": "Mix with 2mL (200 units) BAC water", "frequency": "Dose nightly subcutaneously, 5 days/week", "subcutaneous": "100-300mcg (2-6 units) nightly"}]'::jsonb, '["CJC-1295: Synergistic GH release", "Tesamorelin: Fat reduction"]'::jsonb, '🩹', true, 10, 366.72, 3667.23);

-- Update all peptides to be active
UPDATE peptides SET is_active = true WHERE is_active IS NULL;

-- Create helpful view for grouped peptides
CREATE OR REPLACE VIEW v_peptides_grouped AS
SELECT 
  name,
  category,
  ARRAY_AGG(DISTINCT strength ORDER BY strength) as available_strengths,
  COUNT(*) as variant_count,
  MIN(id) as primary_id,
  MIN(price_per_vial) as min_price,
  MAX(price_per_vial) as max_price
FROM peptides
WHERE is_active = true
GROUP BY name, category
ORDER BY name;

